import { Router, type Request, type Response } from "express";
import { HttpError } from "../errors.ts";
import { callLLM } from "../llm/callLLM.ts";
import type { SessionStore } from "../session/store.ts";
import type { ClarifyQuestion } from "../types.ts";
import type { ClarifyOutput } from "../agents/clarify.ts";
import {
  requireApiKey,
  requireClarificationPairs,
  requireIdeaText,
  requireSession,
} from "./require.ts";

/*
 * POST /api/clarify - build-order step 6: idea -> targeted questions,
 * prepended to the draft. One route serves both rounds:
 *
 *   { ideaText }  round 1 - starts (or restarts) the clarify stage for a
 *                 fresh idea, resetting any previous clarify state.
 *   { answers }   round 2 - the round-1 Q&A pairs (question TEXT + answer,
 *                 blank answer = skipped); the model checks whether the
 *                 answers surfaced anything genuinely new.
 *
 * The stage is capped at 2 rounds (enforced here, not just in the prompt).
 * Responds with only the questions generated by THIS call - the client
 * drives the flow and owns the answers; the session keeps the asked
 * questions (with server-assigned CQ-n ids) for state/debuggability.
 * Clarify state commits only after the LLM call succeeds, so a failed call
 * can simply be retried.
 */

export function clarifyRouter(store: SessionStore): Router {
  const router = Router();

  router.post("/", async (req: Request, res: Response) => {
    const session = requireSession(store, req);
    const apiKey = requireApiKey(req);
    const body = req.body as { ideaText?: unknown; answers?: unknown } | null;

    if (body?.answers === undefined) {
      /* Round 1 */
      const ideaText = requireIdeaText(body);
      const output = await callLLM(
        "clarify",
        { ideaText, priorAnswers: null },
        { session, apiKey },
      );
      const questions = toQuestions(output, 1, 0);
      session.clarify = { ideaText, roundsUsed: 1, questions };
      res.json({ questions });
      return;
    }

    /* Round 2 */
    const clarify = session.clarify;
    if (!clarify) {
      throw new HttpError(
        400,
        "CLARIFY_NOT_STARTED",
        "Answers were submitted before any clarifying questions were asked.",
      );
    }
    if (clarify.roundsUsed >= 2) {
      throw new HttpError(
        400,
        "CLARIFY_ROUNDS_EXHAUSTED",
        "The clarify stage is capped at 2 rounds.",
      );
    }
    const answers = requireClarificationPairs(body.answers);
    const output = await callLLM(
      "clarify",
      { ideaText: clarify.ideaText, priorAnswers: answers },
      { session, apiKey },
    );
    const questions = toQuestions(output, 2, clarify.questions.length);
    clarify.roundsUsed = 2;
    clarify.questions.push(...questions);
    res.json({ questions });
  });

  return router;
}

/* The server assigns stable question ids (models mint none, prompt revision
 * 2026-07-01); numbering continues across rounds within one clarify state. */
function toQuestions(
  output: ClarifyOutput,
  round: number,
  offset: number,
): ClarifyQuestion[] {
  return output.questions.map((q, i) => ({
    id: `CQ-${offset + i + 1}`,
    question: q.question,
    whyItMatters: q.whyItMatters,
    round,
  }));
}
